//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MansymovaKyrsovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> groupId { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> math { get; set; }
        public Nullable<int> rus { get; set; }
        public Nullable<int> literature { get; set; }
        public Nullable<int> fizra { get; set; }
    }
}
